version: "3.9"

services:
  server:
    build:
      dockerfile: Server.Dockerfile
    environment:
      - DB_CONNECTION_STRING=Server=database.sigma.bank;User=sa;Password=SigmaBank47559
    ports:
      - "5959:5959"
    networks:
      sigmanet:
  aspnetcore:
    build:
      dockerfile: AspNetCore.Dockerfile
    environment:
      - DB_CONNECTION_STRING=Server=database.sigma.bank;User=sa;Password=SigmaBank47559
    ports:
      - "6060:6060"
    networks:
      sigmanet:
  data:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    volumes:
      - data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SigmaBank47559
    networks:
      sigmanet:
        aliases:
          - database.sigma.bank

volumes:
  data:

networks:
  sigmanet:
